package impl.entrecine4.persistence;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.entrecine4.model.Movie;
import com.entrecine4.persistence.MovieDAO;

//TODO:This is a sample implementation of a DAO, there's no javadoc until this is a final implementation
//TODO:In all DAOs we can choose between use try/catch sentences or propagate the exceptions
public class MovieJdbcDAO implements MovieDAO
{
	//Variables to use in the class and this way don't be defining all the time the same variables in each method
	private Connection connection = null;
	private PreparedStatement pst = null;
	private ResultSet rs = null;

	@Override
	public Movie get(long movieId) throws SQLException 
	{
		Movie result=null;
		
		pst=connection.prepareStatement("SQL (Option 1: using a .properties file)(Option 2: using string variables located in this class)");
		pst.setLong(1, movieId);
		
		rs=pst.executeQuery();
		if(rs.next())
		{
			result=new Movie();
			result.setId(movieId);
			result.setName(rs.getString("NOMBRE"));
			result.setSynopsis(rs.getString("SINOPSIS"));
			result.setImgPath(rs.getString("RUTA_IMAGEN_CARTEL"));
			result.setMorningPrice(rs.getDouble("PRECIO_MATUTINO"));
			result.setDailyPrice(rs.getDouble("PRECIO_DIARIO"));
			result.setNightPrice(rs.getDouble("PRECIO_NOCHE"));
		}
		
		return result;
	}

	@Override
	public List<Movie> getAll() throws SQLException 
	{
		List<Movie> result=new ArrayList<Movie>();
		
		pst=connection.prepareStatement("SQL (Option 1: using a .properties file)(Option 2: using string variables located in this class)");
		
		rs=pst.executeQuery();
		while(rs.next())
		{
			Movie tempMovie=new Movie();
			tempMovie.setId(rs.getLong("ID_PELICULA"));
			tempMovie.setName(rs.getString("NOMBRE"));
			tempMovie.setSynopsis(rs.getString("SINOPSIS"));
			tempMovie.setImgPath(rs.getString("RUTA_IMAGEN_CARTEL"));
			tempMovie.setMorningPrice(rs.getDouble("PRECIO_MATUTINO"));
			tempMovie.setDailyPrice(rs.getDouble("PRECIO_DIARIO"));
			tempMovie.setNightPrice(rs.getDouble("PRECIO_NOCHE"));
			
			result.add(tempMovie);
		}
		
		return result;
	}

	@Override
	public void save(Movie movie) throws SQLException 
	{
		pst=connection.prepareStatement("SQL (Option 1: using a .properties file)(Option 2: using string variables located in this class)");
		//TODO:The movie id can be generated by the database
		pst.setString(1, movie.getName());
		pst.setString(2, movie.getSynopsis());
		pst.setString(3, movie.getImgPath());
		pst.setDouble(4, movie.getMorningPrice());
		pst.setDouble(5, movie.getDailyPrice());
		pst.setDouble(6, movie.getNightPrice());
		
		pst.executeUpdate();
	}

	@Override
	public void update(Movie movie) throws SQLException 
	{
		pst=connection.prepareStatement("SQL (Option 1: using a .properties file)(Option 2: using string variables located in this class)");
		//TODO:Here we would put only the editable fields
		pst.setString(1, movie.getName());
		pst.setString(2, movie.getSynopsis());
		pst.setString(3, movie.getImgPath());
		pst.setDouble(4, movie.getMorningPrice());
		pst.setDouble(5, movie.getDailyPrice());
		pst.setDouble(6, movie.getNightPrice());
		
		pst.executeUpdate();
	}

	@Override
	public void delete(Movie movie) throws SQLException
	{
		pst=connection.prepareStatement("SQL (Option 1: using a .properties file)(Option 2: using string variables located in this class)");
		pst.setLong(1, movie.getId());
		
		pst.executeUpdate();
	}
}